// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIChartsNameVersionParams creates a new GetAPIChartsNameVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIChartsNameVersionParams() *GetAPIChartsNameVersionParams {
	return &GetAPIChartsNameVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIChartsNameVersionParamsWithTimeout creates a new GetAPIChartsNameVersionParams object
// with the ability to set a timeout on a request.
func NewGetAPIChartsNameVersionParamsWithTimeout(timeout time.Duration) *GetAPIChartsNameVersionParams {
	return &GetAPIChartsNameVersionParams{
		timeout: timeout,
	}
}

// NewGetAPIChartsNameVersionParamsWithContext creates a new GetAPIChartsNameVersionParams object
// with the ability to set a context for a request.
func NewGetAPIChartsNameVersionParamsWithContext(ctx context.Context) *GetAPIChartsNameVersionParams {
	return &GetAPIChartsNameVersionParams{
		Context: ctx,
	}
}

// NewGetAPIChartsNameVersionParamsWithHTTPClient creates a new GetAPIChartsNameVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIChartsNameVersionParamsWithHTTPClient(client *http.Client) *GetAPIChartsNameVersionParams {
	return &GetAPIChartsNameVersionParams{
		HTTPClient: client,
	}
}

/*
GetAPIChartsNameVersionParams contains all the parameters to send to the API endpoint

	for the get API charts name version operation.

	Typically these are written to a http.Request.
*/
type GetAPIChartsNameVersionParams struct {

	/* Name.

	   chart name
	*/
	Name string

	/* Version.

	   chart version
	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API charts name version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIChartsNameVersionParams) WithDefaults() *GetAPIChartsNameVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API charts name version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIChartsNameVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API charts name version params
func (o *GetAPIChartsNameVersionParams) WithTimeout(timeout time.Duration) *GetAPIChartsNameVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API charts name version params
func (o *GetAPIChartsNameVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API charts name version params
func (o *GetAPIChartsNameVersionParams) WithContext(ctx context.Context) *GetAPIChartsNameVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API charts name version params
func (o *GetAPIChartsNameVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API charts name version params
func (o *GetAPIChartsNameVersionParams) WithHTTPClient(client *http.Client) *GetAPIChartsNameVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API charts name version params
func (o *GetAPIChartsNameVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get API charts name version params
func (o *GetAPIChartsNameVersionParams) WithName(name string) *GetAPIChartsNameVersionParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get API charts name version params
func (o *GetAPIChartsNameVersionParams) SetName(name string) {
	o.Name = name
}

// WithVersion adds the version to the get API charts name version params
func (o *GetAPIChartsNameVersionParams) WithVersion(version string) *GetAPIChartsNameVersionParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get API charts name version params
func (o *GetAPIChartsNameVersionParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIChartsNameVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
