// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIChartsParams creates a new GetAPIChartsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIChartsParams() *GetAPIChartsParams {
	return &GetAPIChartsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIChartsParamsWithTimeout creates a new GetAPIChartsParams object
// with the ability to set a timeout on a request.
func NewGetAPIChartsParamsWithTimeout(timeout time.Duration) *GetAPIChartsParams {
	return &GetAPIChartsParams{
		timeout: timeout,
	}
}

// NewGetAPIChartsParamsWithContext creates a new GetAPIChartsParams object
// with the ability to set a context for a request.
func NewGetAPIChartsParamsWithContext(ctx context.Context) *GetAPIChartsParams {
	return &GetAPIChartsParams{
		Context: ctx,
	}
}

// NewGetAPIChartsParamsWithHTTPClient creates a new GetAPIChartsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIChartsParamsWithHTTPClient(client *http.Client) *GetAPIChartsParams {
	return &GetAPIChartsParams{
		HTTPClient: client,
	}
}

/*
GetAPIChartsParams contains all the parameters to send to the API endpoint

	for the get API charts operation.

	Typically these are written to a http.Request.
*/
type GetAPIChartsParams struct {

	/* Limit.

	   limit
	*/
	Limit *int64

	/* Offset.

	   offset
	*/
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API charts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIChartsParams) WithDefaults() *GetAPIChartsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API charts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIChartsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API charts params
func (o *GetAPIChartsParams) WithTimeout(timeout time.Duration) *GetAPIChartsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API charts params
func (o *GetAPIChartsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API charts params
func (o *GetAPIChartsParams) WithContext(ctx context.Context) *GetAPIChartsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API charts params
func (o *GetAPIChartsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API charts params
func (o *GetAPIChartsParams) WithHTTPClient(client *http.Client) *GetAPIChartsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API charts params
func (o *GetAPIChartsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get API charts params
func (o *GetAPIChartsParams) WithLimit(limit *int64) *GetAPIChartsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get API charts params
func (o *GetAPIChartsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get API charts params
func (o *GetAPIChartsParams) WithOffset(offset *int64) *GetAPIChartsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get API charts params
func (o *GetAPIChartsParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIChartsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
