// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/chartmuseum-client-go/models"
)

// GetAPIChartsNameReader is a Reader for the GetAPIChartsName structure.
type GetAPIChartsNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIChartsNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIChartsNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAPIChartsNameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAPIChartsNameOK creates a GetAPIChartsNameOK with default headers values
func NewGetAPIChartsNameOK() *GetAPIChartsNameOK {
	return &GetAPIChartsNameOK{}
}

/*
GetAPIChartsNameOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIChartsNameOK struct {
	Payload []*models.RepoChartVersion
}

// IsSuccess returns true when this get Api charts name o k response has a 2xx status code
func (o *GetAPIChartsNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api charts name o k response has a 3xx status code
func (o *GetAPIChartsNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api charts name o k response has a 4xx status code
func (o *GetAPIChartsNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api charts name o k response has a 5xx status code
func (o *GetAPIChartsNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api charts name o k response a status code equal to that given
func (o *GetAPIChartsNameOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAPIChartsNameOK) Error() string {
	return fmt.Sprintf("[GET /api/charts/{name}][%d] getApiChartsNameOK  %+v", 200, o.Payload)
}

func (o *GetAPIChartsNameOK) String() string {
	return fmt.Sprintf("[GET /api/charts/{name}][%d] getApiChartsNameOK  %+v", 200, o.Payload)
}

func (o *GetAPIChartsNameOK) GetPayload() []*models.RepoChartVersion {
	return o.Payload
}

func (o *GetAPIChartsNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIChartsNameDefault creates a GetAPIChartsNameDefault with default headers values
func NewGetAPIChartsNameDefault(code int) *GetAPIChartsNameDefault {
	return &GetAPIChartsNameDefault{
		_statusCode: code,
	}
}

/*
GetAPIChartsNameDefault describes a response with status code -1, with default header values.

GetAPIChartsNameDefault get API charts name default
*/
type GetAPIChartsNameDefault struct {
	_statusCode int

	Payload models.GinH
}

// Code gets the status code for the get API charts name default response
func (o *GetAPIChartsNameDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get API charts name default response has a 2xx status code
func (o *GetAPIChartsNameDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get API charts name default response has a 3xx status code
func (o *GetAPIChartsNameDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get API charts name default response has a 4xx status code
func (o *GetAPIChartsNameDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get API charts name default response has a 5xx status code
func (o *GetAPIChartsNameDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get API charts name default response a status code equal to that given
func (o *GetAPIChartsNameDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetAPIChartsNameDefault) Error() string {
	return fmt.Sprintf("[GET /api/charts/{name}][%d] GetAPIChartsName default  %+v", o._statusCode, o.Payload)
}

func (o *GetAPIChartsNameDefault) String() string {
	return fmt.Sprintf("[GET /api/charts/{name}][%d] GetAPIChartsName default  %+v", o._statusCode, o.Payload)
}

func (o *GetAPIChartsNameDefault) GetPayload() models.GinH {
	return o.Payload
}

func (o *GetAPIChartsNameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
