// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetChartsFilenameParams creates a new GetChartsFilenameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetChartsFilenameParams() *GetChartsFilenameParams {
	return &GetChartsFilenameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetChartsFilenameParamsWithTimeout creates a new GetChartsFilenameParams object
// with the ability to set a timeout on a request.
func NewGetChartsFilenameParamsWithTimeout(timeout time.Duration) *GetChartsFilenameParams {
	return &GetChartsFilenameParams{
		timeout: timeout,
	}
}

// NewGetChartsFilenameParamsWithContext creates a new GetChartsFilenameParams object
// with the ability to set a context for a request.
func NewGetChartsFilenameParamsWithContext(ctx context.Context) *GetChartsFilenameParams {
	return &GetChartsFilenameParams{
		Context: ctx,
	}
}

// NewGetChartsFilenameParamsWithHTTPClient creates a new GetChartsFilenameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetChartsFilenameParamsWithHTTPClient(client *http.Client) *GetChartsFilenameParams {
	return &GetChartsFilenameParams{
		HTTPClient: client,
	}
}

/*
GetChartsFilenameParams contains all the parameters to send to the API endpoint

	for the get charts filename operation.

	Typically these are written to a http.Request.
*/
type GetChartsFilenameParams struct {

	/* Filename.

	   <chart-name>-<version>.tgz or <chart-name>-<version>.tgz.prov
	*/
	Filename string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get charts filename params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetChartsFilenameParams) WithDefaults() *GetChartsFilenameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get charts filename params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetChartsFilenameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get charts filename params
func (o *GetChartsFilenameParams) WithTimeout(timeout time.Duration) *GetChartsFilenameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get charts filename params
func (o *GetChartsFilenameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get charts filename params
func (o *GetChartsFilenameParams) WithContext(ctx context.Context) *GetChartsFilenameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get charts filename params
func (o *GetChartsFilenameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get charts filename params
func (o *GetChartsFilenameParams) WithHTTPClient(client *http.Client) *GetChartsFilenameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get charts filename params
func (o *GetChartsFilenameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilename adds the filename to the get charts filename params
func (o *GetChartsFilenameParams) WithFilename(filename string) *GetChartsFilenameParams {
	o.SetFilename(filename)
	return o
}

// SetFilename adds the filename to the get charts filename params
func (o *GetChartsFilenameParams) SetFilename(filename string) {
	o.Filename = filename
}

// WriteToRequest writes these params to a swagger request
func (o *GetChartsFilenameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param filename
	if err := r.SetPathParam("filename", o.Filename); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
