// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/chartmuseum-client-go/models"
)

// GetAPIChartsReader is a Reader for the GetAPICharts structure.
type GetAPIChartsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIChartsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIChartsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAPIChartsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAPIChartsOK creates a GetAPIChartsOK with default headers values
func NewGetAPIChartsOK() *GetAPIChartsOK {
	return &GetAPIChartsOK{}
}

/*
GetAPIChartsOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIChartsOK struct {
	Payload models.ChartmuseumServerMultitenantGetAllChartsOutput
}

// IsSuccess returns true when this get Api charts o k response has a 2xx status code
func (o *GetAPIChartsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api charts o k response has a 3xx status code
func (o *GetAPIChartsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api charts o k response has a 4xx status code
func (o *GetAPIChartsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api charts o k response has a 5xx status code
func (o *GetAPIChartsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api charts o k response a status code equal to that given
func (o *GetAPIChartsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAPIChartsOK) Error() string {
	return fmt.Sprintf("[GET /api/charts][%d] getApiChartsOK  %+v", 200, o.Payload)
}

func (o *GetAPIChartsOK) String() string {
	return fmt.Sprintf("[GET /api/charts][%d] getApiChartsOK  %+v", 200, o.Payload)
}

func (o *GetAPIChartsOK) GetPayload() models.ChartmuseumServerMultitenantGetAllChartsOutput {
	return o.Payload
}

func (o *GetAPIChartsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIChartsDefault creates a GetAPIChartsDefault with default headers values
func NewGetAPIChartsDefault(code int) *GetAPIChartsDefault {
	return &GetAPIChartsDefault{
		_statusCode: code,
	}
}

/*
GetAPIChartsDefault describes a response with status code -1, with default header values.

GetAPIChartsDefault get API charts default
*/
type GetAPIChartsDefault struct {
	_statusCode int

	Payload models.GinH
}

// Code gets the status code for the get API charts default response
func (o *GetAPIChartsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get API charts default response has a 2xx status code
func (o *GetAPIChartsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get API charts default response has a 3xx status code
func (o *GetAPIChartsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get API charts default response has a 4xx status code
func (o *GetAPIChartsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get API charts default response has a 5xx status code
func (o *GetAPIChartsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get API charts default response a status code equal to that given
func (o *GetAPIChartsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetAPIChartsDefault) Error() string {
	return fmt.Sprintf("[GET /api/charts][%d] GetAPICharts default  %+v", o._statusCode, o.Payload)
}

func (o *GetAPIChartsDefault) String() string {
	return fmt.Sprintf("[GET /api/charts][%d] GetAPICharts default  %+v", o._statusCode, o.Payload)
}

func (o *GetAPIChartsDefault) GetPayload() models.GinH {
	return o.Payload
}

func (o *GetAPIChartsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
